name: Pagrr 
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 12.7.0

settings:
  DEVELOPMENT_TEAM: 68BLC88PQ9
targets:
  Pagrr:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 26.0
    sources: 
      - path: Pagrr
      - path: AppIcon.icon
        buildPhase: resources
    scheme: {}
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAnalyticsCore
      - package: Firebase
        product: FirebaseAppCheck
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseMessaging
    settings:
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_NAME: Pagrr
      INFOPLIST_FILE: Pagrr/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: de.valentinlehmann.pagrr
      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: 1
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
