name: Pagrr 
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 12.7.0

settings:
  DEVELOPMENT_TEAM: 68BLC88PQ9
targets:
  Pagrr:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 26.0
    sources: 
      - path: Pagrr
      - path: AppIcon.icon
        buildPhase: resources
    scheme: {}
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAnalyticsCore
      - package: Firebase
        product: FirebaseAppCheck
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseMessaging
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_NAME: Pagrr
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 2
        INFOPLIST_KEY_CFBundleDisplayName: Pagrr
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.developer-tools"
        INFOPLIST_FILE: Pagrr/Info.plist
        CODE_SIGN_ENTITLEMENTS: Pagrr/Entitlements.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: de.valentinlehmann.pagrr
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: 1
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
        PROVISIONING_PROFILE_SPECIFIER: ""
        IPHONEOS_DEPLOYMENT_TARGET: 26.0
        CODE_SIGN_IDENTITY: ""
      configs:
        Debug:
          "CODE_SIGN_IDENTITY[sdk=iphoneos*]": "iPhone Developer"
          "PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]": "match Development de.valentinlehmann.pagrr"
        Release:
          "CODE_SIGN_IDENTITY[sdk=iphoneos*]": "iPhone Distribution"
          "PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]": "match AppStore de.valentinlehmann.pagrr"
