# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    api_key = load_api_key
    match(type: 'appstore')
    update_build_number
    build_app(scheme: "Pagrr")
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end

desc "Load App Store Connect API key"
lane :load_api_key do
  app_store_connect_api_key(
    duration: 300, # This Token is valid for 300s
    key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
    is_key_content_base64: true,
    in_house: false
  )
end

desc "Set build number to current date/time"
lane :update_build_number do
  # Increment build number to current date
  build_number = Time.new.strftime("%Y%m%d%H%M")

  increment_build_number(
    build_number: build_number
  )
end